spring:
  application:
    name: "score-service"
  main:
    banner-mode: "off"
  jackson:
    default-property-inclusion: non_null
    serialization:
      INDENT_OUTPUT: true
  data:
    mongodb:
      database: score-service-local
server:
  port: 8080
  compression:
    enabled: true
    mime-types: appilication/json
    min-response-size: 1024
logging:
  level:
    org.springframework.data.*: DEBUG
